preset: simple
releaseLenient: false
releasePrefix: "v"
stateFile: build/nyx-state.json
scheme: SEMVER

changelog:
  path: build/CHANGELOG.md
  template: .nyx/CHANGELOG.tpl
  sections:
    Added: "^feat$"
    Fixed: "^fix$"
  substitutions:
    "(?m)#([0-9]+)(?s)": "[#%s](https://github.com/AndroidIDEOfficial/AndroidIDE/issues/%s)"

releaseAssets:
  apk_arm64:
    fileName: "androidide-{{version}}-arm64-v8a.apk"
    description: "AndroidIDE {{version}} arm64-v8a release APK"
    path: app-arm64-v8a-arm64-v8a-release.apk
    type: application/octet-stream
  apk_arm:
    fileName: "androidide-{{version}}-armeabi-v7a.apk"
    description: "AndroidIDE {{version}} armeabi-v7a release APK"
    path: app-armeabi-v7a-armeabi-v7a-release.apk
    type: application/octet-stream

releaseTypes:
  enabled:
    - mainline
    - internal
  publicationServices:
    - github
  remoteRepositories:
    - origin
  items:
    mainline:
      description: "{{#fileContent}}build/CHANGELOG.md{{/fileContent}}"
      gitPush: true
      gitTag: true
      publish: true
      matchBranches: "^(master|main)$"
      matchWorkspaceStatus: "CLEAN"
      matchEnvironmentVariables:
        CI: "^true$"
        ReleaseAndroidIDE: "^true$"
    internal:
      description: "{{#fileContent}}build/CHANGELOG.md{{/fileContent}}"
      collapseVersions: true
      collapsedVersionQualifier: "internal"
      gitPush: false
      gitTag: false
      publish: false
      identifiers:
        -
          qualifier: "branch"
          value: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
          position: "BUILD"
        -
          qualifier: "commit"
          value: "{{#short7}}{{releaseScope.finalCommit}}{{/short7}}"
          position: "BUILD"
        - 
          qualifier: "timestamp"
          value: "{{#timestampYYYYMMDDHHMMSS}}{{timestamp}}{{/timestampYYYYMMDDHHMMSS}}"
          position: "BUILD"

services:
    github:
      type: GITHUB
      options:
        REPOSITORY_OWNER: "AndroidIDEOfficial"
        REPOSITORY_NAME: "AndroidIDE"
        AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
