name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide a proper title and description to the issue.
        
        A **GOOD** issue title describes the issue briefly. For example :
        - [Bug]: Cannot use bluetooth keyboard in terminal
        - [Feature]: Add support for previewing custom view in UI Designer
        - [Feature]: Add preferences to configure Java code formatting
        
        Examples of a **BAD** title :
        - File editing issues
        - Terminal emulator
        - App crashed
        - Error
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue properly.
      placeholder: Describe the error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What's the expected behavior?
      description: Tell us what is the expected behavior.
      placeholder: Describe the expected behavior.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version of AndroidIDE you're using?
      multiple: false
      options:
        - v2.1.2 (debug builds)
        - v2.1.1
        - v2.1.0
        - v2.0.1
        - v2.0.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: not-a-duplicate
    attributes:
      label: Duplicate issues
      description: Please make sure that there are no similar issues opened. Duplicate issues will be closed directly. If there are any similar looking issues, leave a comment there.
      options:
        - label: This issue has not been reported yet.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/itsaky/AndroidIDE/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
