name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide a proper title and
        description to the issue.
        
        **Note: Before submitting a bug report, please make sure that the issue hasn't been reported
        before. Check the existing issues and confirm that this is not a duplicate.**
  
        **By submitting this issue, you agree to follow the project's
        [code of conduct](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/CODE_OF_CONDUCT.md).**
      
        **Please check and verify that you are using the latest version of AndroidIDE before
        submitting this bug report.**
        
        **Please ensure that you provide complete and accurate information to expedite the
        bug resolution process. Incomplete reports may be closed without further investigation.**
        
        **All issues must be reported in English. Issues in other languages may be closed
        without further consideration.**
        
        **Thank you for your understanding and cooperation.**
  - type: checkboxes
    id: checklist
    attributes:
      label: Issue Checklist
      options:
        - label: I confirm that this issue is not a duplicate and hasn't been reported before.
          required: true
        - label: I agree to follow the project's code of conduct.
          required: true
        - label: I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.
          required: true
  - type: checkboxes
    id: additional-terms
    attributes:
      label: Additional terms
      options:
        - label: I understand that providing incomplete or inaccurate information may result in the issue being closed.
          required: true
        - label: I agree to provide all requested details promptly for a comprehensive bug report.
          required: true
  - type: textarea
    id: issue-explanation
    attributes:
      label: Issue explanation
      description: Please provide a detailed explanation of the issue you are facing.
      placeholder: Describe the issue here. Logs or stacktraces must not be entered here.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you expected to happen.
      placeholder: Logs or stacktraces must not be entered here.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version name
      description: Specify the version name of AndroidIDE you are using.
      placeholder: Go to IDE Preferences -> About AndroidIDE and click on the version name to copy it.
    validations:
      required: true
  - type: dropdown
    id: download-source
    attributes:
      label: Download source
      description: Did you download AndroidIDE from GitHub or F-Droid?
      options:
        - GitHub
        - F-Droid
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Include relevant log output if reporting a crash or build error. This can be
        optional, but it is mandatory if reporting a crash or build error.
      placeholder: Enter relevant log output or stacktraces here.
      render: bash
